[project]
name = "recommendersystems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "mkdocs-material>=9.7.0",
    "pandas>=2.3.3",
    "ruff>=0.14.4",
    "seaborn>=0.13.2",
    "torch==2.1.1",
    "numpy==1.26.4",
    "recpack>=0.3.6",
    "hyperopt>=0.2.7",
    "ydata-profiling>=4.12.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-watcher>=0.6.3",
]

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["notebooks"]
force-exclude = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
filterwarnings = [
    "ignore:pkg_resources is deprecated as an API:UserWarning",
]
